### PR TITLE
Refactor/get all spaces listener

### PR DESCRIPTION
**Pull request by fboechats**
refactor: factor out getAllSpaces listener

Factor out the getAllSpaces listener to its own file.

Note: I added a "All" in the name to be more intuitive the difference between this listener and the getSpace listener.

refs #104

### CODE REVIEW

**Comment by juancarlosfarah** [comment]
@fboechats, can you rebase please as there have been some recent changes that were merged after your PR.

Also, could you rename the method and files to `getSpaces` (plural)? This is how we are handling the difference in this repo. This is mainly to match the types and channels, which are called `GET_SPACES...`. Also, because `getAllSpaces` implies that we are getting all of the possible spaces. Most likely this is a pageable, which means that you can pass some params and get a given `limit` of spaces after a `skip` and a `sort`.

Thanks!

**Comment by juancarlosfarah** [comment]
@fboechats, thanks for fixing this. Could you please squash your commits into one? That way the commit history stays clean.

Here is how to do it in case you haven't done it before (subtitle: *The hard(er) and less flexible way*):

https://gist.github.com/patik/b8a9dc5cd356f9f6f980#the-harder-and-less-flexible-way

The commit message can then be something like: 

```
refactor: factor out getSpaces listener

Factor out the getSpaces listener to its own file.

refs #104
```

Thanks!

**Comment by fboechats** [comment]
Can I create another PR?? I had a problem with the fork and lost connection with this PR.

**Comment by juancarlosfarah** [comment]
Hi @fboechats, yes of course! You can close this PR and create a new one with the same changes and the correct commit.

**Pull request closed without merging**
