### PR TITLE
make dialogs modals

### PR DESCRIPTION
**Pull request by bootsa**
make the file and message pop ups modals (children of the main window) so that they don't open up a second app instance/dock icon (at least in Linux, haven't test Windows or MacOS), and stay on top of the main window preventing getting lost confusingly behind main window.

Disables main window when dialogues are open - can't think of a time when you wouldn't want this.

### CODE REVIEW

**Comment by bootsa** [comment]
Oops, missed the open refactor PRs (#127, #128 & #129) that actually implement this. Would be nice to have them resolved.

**Comment by juancarlosfarah** [comment]
@bootsa, you can now resume this as #127, #128, and #129 are now in `master`.

**Comment by bootsa** [comment]
Sorry, been away for a couple of weeks.

Not sure if I submitted it correctly as I did it on another branch and referenced here. Does that work or do I need to create another pull request?

**Comment by juancarlosfarah** [comment]
Hi @bootsa, you've correctly fixed the conflicts, but you've overridden your changes. We can either (1) close this PR and you can do your changes in a fresh new one. Or (2) you can add your new changes to this PR.

I would prefer option (1).

**Comment by bootsa** [comment]
Hi @juancarlosfarah,

Oops! OK, have now created a new pull request #182

**Pull request closed without merging**
